# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 231fb3a39c809fc6af2c650cad42cf31173066f3f2841a38acb656410f4c32bf27442e39dc0910f4483dc2532f4d99e93b191ad8ce75002cc4034ec64a12c23f

test:
  secret_key_base: 36d74efa8f4711faff92386b6d4f83f8e57fa58b7de5f00f735f02596f855c56cd4b4b116e75749d378806acce2f36d382b41a3c50a85a65ab354c1ae17b59bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
